### ISSUE TITLE
suggestion to run velocity commands (proxy ones)

### ISSUE THREAD

**Issue by jokbon** [ILoveAMac/BlocksToCommands#10]
suggestion to run velocity commands (proxy ones)
if alredy implemented improve doc

**Comment by ILoveAMac** [comment]
Hello, it has been quite some time since I have worked on this plugin. I made it back when I was in 10th grade. I am now a 3rd year engineering student and don't really have time to support this plugin.

However, "velocity commands" have literally no meaning to me. If you have a feature suggestion you have to be more desciptive 🙂

After some research I assume you're referring to https://velocitypowered.com ?
If so I have no intention of supporting it, I am not sure if it's even compatible with spigot/buckit. Additionally this plugin only runs commands it does not interface with other plugins except vault. So I'm not even sure what you mean by adding support of it.
